server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:the-movies-db
    driver-class-name: org.h2.Driver
    username: test
    password:

  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: false
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher